version: '3'

services:
  xds-server:
    image: tak2siva/envoy-pilot:v0.2.7
    restart: on-failure
    networks:
      - xds-infra
    ports:
      - "9090:9090"
    volumes:
      - $PWD/env_values.txt:/.env
      - $PWD/wait-for-command.sh:/scripts/wait-for-command.sh
    depends_on:
      - consul-server-bootstrap
    #command: ["./scripts/wait-for-it.sh", "consul-server-bootstrap:8500/v1/status/leader", "--", "echo", "'its up'"]
    command: "sh -c 'apk add --no-cache curl; chmod +x /scripts/wait-for-command.sh; sh /scripts/wait-for-command.sh -t 30 -c \"curl -f http://consul-server-bootstrap:8500/v1/status/leader\" && ./Envoy-Pilot'"

  consul-server-bootstrap:
    image: consul:latest
    networks:
      - xds-infra
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -dev -ui -client 0.0.0.0"

networks:
  xds-infra: